In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
root_dir = '/content/drive/MyDrive/Models_exp2.10'

In [ ]:
import os
import multiprocessing
import numpy as np
import cv2
import time
import shutil

import torch

import keras
from tensorflow.keras.applications import EfficientNetB0

In [ ]:
!nvidia-smi

Fri Apr 30 17:10:28 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    29W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/
#efficient nets are a lot easier to work with in keras
from keras import layers

def build_model(num_classes, IMG_SIZE):
    inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

    eff_model = EfficientNetB0(include_top=False, input_tensor=inputs, weights="imagenet")

    # Freeze the pretrained weights
    eff_model.trainable = False

    # Rebuild top
    x = layers.GlobalAveragePooling2D(name="avg_pool")(eff_model.output)
    x = layers.BatchNormalization()(x)

    # top_dropout_rate = 0.2
    # x = layers.Dropout(top_dropout_rate, name="top_dropout")(x)
    outputs = layers.Dense(num_classes, activation="softmax", name="pred")(x)

    # Compile
    model = keras.Model(inputs, outputs, name="EfficientNet")
    optimizer = keras.optimizers.Adam()
    model.compile(
        optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"]
    )
    return model

In [ ]:
class Date_3d_Cached(torch.utils.data.Dataset):
    def __init__(self, x, y):
      self.x = torch.from_numpy(x)
      self.y = torch.from_numpy(y)
    
    def __len__(self):
      return self.x.shape[0]

    def __getitem__(self, idx):
      x = self.x[idx]
      return x, self.y[idx]

In [ ]:
views = ['bottom', 'side_1', 'side_2', 'side_3', 'side_4', 'top', 'top_1', 'top_2', 'top_3', 'top_4', 'bot_1', 'bot_2', 'bot_3', 'bot_4']
x = np.load('/content/drive/MyDrive/Cache/x_compressed.npz')['arr_0']
y = np.load('/content/drive/MyDrive/Cache/y.npy')

In [ ]:
reshaped_x = x.transpose([0, 1, 3, 4, 2])

In [ ]:
one_hot_y = keras.utils.to_categorical(y, 10)

In [ ]:
training_data = Date_3d_Cached(reshaped_x, one_hot_y)
#90/10 train val split
train_len = int(len(training_data) * .9)
val_len = len(training_data) - train_len

In [ ]:
#using pytorch data loader to keep splits the same
train_set, val_set = torch.utils.data.random_split(training_data, [train_len, val_len],torch.Generator().manual_seed(42))

In [ ]:
print(os.cpu_count())
print(train_len)
print(val_len)

4
3591
400


In [ ]:
x, y = train_set[:]
x = x.numpy()
y = y.numpy()

In [ ]:
val_x, val_y = val_set[:]
val_x = val_x.numpy()
val_y = val_y.numpy()


In [ ]:
del train_set
del val_set

del training_data

In [ ]:
del one_hot_y
del reshaped_x

In [ ]:
#https://stackoverflow.com/questions/60567679/save-keras-model-weights-directly-to-bytes-memory
class Save_Best_Weights(keras.callbacks.Callback):   
  def __init__(self, min=True, metric='val_loss'):
      super(Save_Best_Weights, self).__init__()
      self.best = np.Inf
      self.metric = metric
      self.min = min
      if not min:
        self.best = self.best * - 1


  def on_epoch_end(self, epoch, logs=None):
      current_metric = logs.get(self.metric)
      if self.min:
        if np.less(current_metric, self.best):
            self.best = current_metric            
            self.best_weights = model.get_weights() 
            self.name = 'ep_' + str(epoch) + '_' + self.metric + "_" + str(self.best)
            print('saved new ' + self.metric)
      else:
        if np.greater(current_metric, self.best):
            self.best = current_metric            
            self.best_weights = model.get_weights() 
            self.name = 'ep_' + str(epoch) + '_' + self.metric + "_" + str(self.best)
            print('saved new ' + self.metric) 


In [19]:
batch_size = 32
epochs = 100

if not os.path.exists(root_dir):
    os.makedirs(root_dir)


for idx, view in enumerate(views):
    this_dir = os.path.join(root_dir, str(idx) + '_' + view)
    if not os.path.exists(this_dir):
      os.makedirs(this_dir)
    model = build_model(10, 224)
    print(view)
    loss_cp = Save_Best_Weights(
    )

    acc_cp = Save_Best_Weights(
        metric="val_accuracy",
        min=False
    )

    logger = keras.callbacks.CSVLogger(os.path.join(this_dir, 'logs.csv'))
      
    
    batch_x = x[:, idx, ...]
    batch_val_x = val_x[:, idx, ...]

    model.fit(batch_x, y, batch_size, epochs, callbacks=[loss_cp, acc_cp, logger], validation_data=(batch_val_x, val_y))


    #loss saving
    model.set_weights(loss_cp.best_weights)
    model.save(os.path.join(this_dir, loss_cp.name))

    #acc saving
    model.set_weights(acc_cp.best_weights)
    model.save(os.path.join(this_dir, acc_cp.name))
          

      

print('Finished Training')

bottom
Epoch 1/100
113/113 [==============================] - 10s 50ms/step - loss: 1.3980 - accuracy: 0.5468 - val_loss: 0.9372 - val_accuracy: 0.7850
saved new val_loss
saved new val_accuracy
Epoch 2/100
113/113 [==============================] - 4s 39ms/step - loss: 0.5884 - accuracy: 0.8151 - val_loss: 0.6336 - val_accuracy: 0.8375
saved new val_loss
saved new val_accuracy
Epoch 3/100
113/113 [==============================] - 4s 39ms/step - loss: 0.4638 - accuracy: 0.8426 - val_loss: 0.5156 - val_accuracy: 0.8400
saved new val_loss
saved new val_accuracy
Epoch 4/100
113/113 [==============================] - 4s 39ms/step - loss: 0.3949 - accuracy: 0.8670 - val_loss: 0.4894 - val_accuracy: 0.8325
saved new val_loss
Epoch 5/100
113/113 [==============================] - 4s 39ms/step - loss: 0.3420 - accuracy: 0.8909 - val_loss: 0.4872 - val_accuracy: 0.8500
saved new val_loss
saved new val_accuracy
Epoch 6/100
113/113 [==============================] - 4s 39ms/step - loss: 0.3262 - 

In [ ]:
import pandas as pd
     
# dictionary of lists  
this_dict = {'training loss': training_loss_list, 'training acc': training_acc_list, 'val loss': val_loss_list, 'val acc':val_acc_list}  
       
df = pd.DataFrame(this_dict) 
    
# saving the dataframe 
df.to_csv(os.path.join(root_dir, 'logs.csv'))

In [22]:
y_int = y.argmax(1)

In [25]:
unique, counts = np.unique(y_int, return_counts=True)
dict(zip(unique, counts))

{0: 183, 1: 178, 2: 362, 3: 177, 4: 312, 5: 463, 6: 617, 7: 416, 8: 787, 9: 96}

In [26]:
unique, counts = np.unique(val_y.argmax(1), return_counts=True)
dict(zip(unique, counts))

{0: 17, 1: 22, 2: 30, 3: 23, 4: 32, 5: 52, 6: 63, 7: 49, 8: 102, 9: 10}

In [29]:
np.savez_compressed('/content/drive/MyDrive/Cache/keras/train_val', x=x, y=y, x_val=val_x, y_val=val_y)

In [28]:
print(val_y)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
print(inputs.shape)

In [ ]:
cp = torch.load(os.path.join(root_dir, 'last.pt'))
model.load_state_dict(cp['state_dict'])
optimizer.load_state_dict(cp['optimizer'])
last_epoch_done = cp['epoch'] - 1

In [ ]:
#continue training


if not os.path.exists(root_dir):
    os.makedirs(root_dir)


low_val_loss = 30000000
best_acc = -1
epoch = 0

val_loss_path = None
acc_path = None
#https://stackoverflow.com/questions/8078330/csv-writing-within-loop
import csv
with open(os.path.join(root_dir, 'logs2.csv'), 'w') as file_csv:
  writer=csv.writer(file_csv, delimiter=',',lineterminator='\n',)
  writer.writerow(['epoch', 'loss', 'acc', 'val_loss', 'val_acc'])


  for epoch in range(last_epoch_done, 101):
      row = [epoch]
      is_best = False
      running_loss = 0.0
      correct = 0
      total = 0

      model.train()

      t0 = time.time()
      for i, data in enumerate(training_loader):
          # get the inputs; data is a list of [inputs, labels]
          inputs, labels = data

          # for this_view in range(inputs.shape[1]):
          #   if np.random.randint(0, 4) == 0:
          #     inputs[:, this_view, ...] = 1.0

          inputs = inputs.to(device)
          labels = labels.to(device)

          # zero the parameter gradients
          optimizer.zero_grad()

          # forward + backward + optimize
          outputs = model(inputs)
          loss = criterion(outputs, labels)
          loss.backward()
          optimizer.step()

          # print statistics
          correct += (outputs.argmax(1) == labels).float().sum() #https://stackoverflow.com/questions/51503851/calculate-the-accuracy-every-epoch-in-pytorch
          total += labels.shape[0]
          running_loss += loss.item()

      print('epoch', epoch)
      
      print('{} seconds'.format(time.time() - t0))
      print('loss', running_loss)
      row.append(running_loss)
      running_loss = 0.0

      accuracy = 100 * correct / total
      print("Accuracy = {}".format(accuracy))
      row.append(torch.IntTensor.item(accuracy))
      correct = 0
      total= 0

      running_loss = 0.0
      correct = 0
      total = 0

      optimizer.zero_grad()
      model.eval()
      t0 = time.time()
      with torch.no_grad():
          for i, data in enumerate(val_loader):
              
              # get the inputs; data is a list of [inputs, labels]
              inputs, labels = data
              inputs = inputs.to(device)
              labels = labels.to(device)            


              # forward + backward + optimize
              outputs = model(inputs)
              loss = criterion(outputs, labels)

              correct += (outputs.argmax(1) == labels).float().sum() #https://stackoverflow.com/questions/51503851/calculate-the-accuracy-every-epoch-in-pytorch
              total += labels.shape[0]
              running_loss += loss.item()

      print('{} seconds'.format(time.time() - t0))
      print('val loss', running_loss)
      row.append(running_loss)
      

      accuracy = 100 * correct / total
      print(" Val Accuracy = {}".format(accuracy))
      row.append(torch.IntTensor.item(accuracy))

      model_name = 'ep_' + str(epoch) + '_loss_' + str(running_loss) + '_acc_' + str(accuracy) + '.pt'
      full_model_path = os.path.join(root_dir, model_name)
      checkpoint = {
          'epoch': epoch + 1,
          'state_dict': model.state_dict(),
          'optimizer': optimizer.state_dict()
      }
      if running_loss < low_val_loss:
        if val_loss_path and os.path.exists(val_loss_path):
          open(val_loss_path, 'w').close() #overwrite and make the file blank instead - ref: https://stackoverflow.com/a/4914288/3553367
          os.remove(val_loss_path)
        val_loss_path = full_model_path.replace('.pt', 'val_loss_best.pt')
        save_ckp(model, val_loss_path)
        low_val_loss = running_loss
        print('new low loss')

      if accuracy > best_acc:
        if acc_path and os.path.exists(acc_path):
          open(acc_path, 'w').close() #overwrite and make the file blank instead - ref: https://stackoverflow.com/a/4914288/3553367
          os.remove(acc_path)
        acc_path = full_model_path.replace('.pt', 'acc_best.pt')
        save_ckp(model, acc_path)
        best_acc = accuracy
        print('new best acc')
      full_model_path = os.path.join(root_dir, 'last.pt')
      save_ckp(checkpoint, full_model_path)
          

      

      correct = 0
      total= 0
      running_loss = 0.0
      writer.writerow(row)
  print('Finished Training')